# http://www.appveyor.com/docs/appveyor-yml
image: Visual Studio 2019

version: '{build}'

environment:
  nodejs_version: '16'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --immutable --immutable-cache

test_script:
  - yarn run test

# Disable automatic builds
build: false
